name: Build and Publish Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build_wheels:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/OmarSiwy/gRPCNvidia:main
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # Workaround for https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    needs: [build_wheels]
    name: Make Python source distribution
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/OmarSiwy/gRPCNvidia:main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # Workaround for https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - uses: actions/checkout@v3
      - name: Build SDist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/OmarSiwy/gRPCNvidia:main
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # Workaround for https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
