name: Run Docker Google Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/OmarSiwy/gRPCNvidia/test:main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set ownership
        run: |
          # Workaround for https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image with Google Tests
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        load: true
        build-args: |
          BUILD_TESTS=ON
          BUILD_PYTHON=OFF

    - name: Run Google Test
      run: |
        cd build && ctest
